name: OpenAseMdao
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - pandas
  - pytest
  - scipy
  - seaborn
  - ca-certificates
  - numpy
  - h5py
  - plotly
  - sympy
  - jupyter
  - ipywidgets
  - pip:
      - openmdao
      - pyxdsm
      - casadi
      - pint